### PR TITLE
Rework Analyzer Topology

### PR DESCRIPTION
**Pull request by nscuro**
Based on Alioune's suggestions in https://github.com/mehab/DTKafkaPOC/issues/50#issuecomment-1288799243.

The topics used by this application have been renamed to better signal their purpose:

| Topic | Description | Key | Value |
|:----|:-----|:------|:-------|
| component-analysis | Components submitted by the API server for analysis (prev. EventNew) | Component UUID | Component Details |
| component-analysis-cpe | Components re-keyed to CPE | Component CPE | Component Details |
| component-analysis-purl | Components re-keyed to PURL | Component PURL | Component Details |
| component-analysis-swid | Components re-keyed to SWID | Component SWID Tag ID | Component Details |
| component-analysis-vuln | Vulnerability analysis results as emitted by individual analyzers (OSS Index, Snyk) | Component Identity (CPE, PURL, SWID Tag ID) | Vulnerability Details, Analyzer Identity |
| component-vuln-analysis-result | Vulnerability analysis results for consumption by API server | Component UUID | Vulnerability Details, Analyzer Identity |

This implementation will make all dedicated producers using the producer API (`org.acme.producer` package) obsolete. The same is true for all individual consumers and streams defined in the `org.acme.consumer` package.

While the application is running, the topology can be visualized in the Quarkus dev console at http://localhost:8089/q/dev/io.quarkus.quarkus-kafka-streams/kafka-streams-topology

topology

### CODE REVIEW

**Comment by nscuro** [comment]
@syalioune Please don't sweat it, it's still very rough on the edges and has lots of duplicated and unused code. :sweat_smile:

**Comment by nscuro** [comment]
Current output of scanning two components with the same PURL twice in close succession:

```
Received component: 2bda3139-647f-47ff-9c35-ffc16adf3076
Re-keyed component: a4396bd6-631c-428e-822a-f2759a50a6df -> pkg:maven/com.fasterxml.jackson.core/jackson-databind@2.13.1
Joined: pkg:maven/com.fasterxml.jackson.core/jackson-databind@2.13.1 -> VulnerabilityResultAggregate(component=pkg:maven/com.fasterxml.jackson.core/jackson-databind@2.13.1, vulnerabilityResults=null)
Cache miss: pkg:maven/com.fasterxml.jackson.core/jackson-databind@2.13.1
Performing OSS Index analysis for 1 components: [pkg:maven/com.fasterxml.jackson.core/jackson-databind@2.13.1]
Performing Snyk analysis for 1 components: [pkg:maven/com.fasterxml.jackson.core/jackson-databind@2.13.1]
Re-keying result: pkg:maven/com.fasterxml.jackson.core/jackson-databind@2.13.1 -> a4396bd6-631c-428e-822a-f2759a50a6df
Re-keying result: pkg:maven/com.fasterxml.jackson.core/jackson-databind@2.13.1 -> a4396bd6-631c-428e-822a-f2759a50a6df
Re-keying result: pkg:maven/com.fasterxml.jackson.core/jackson-databind@2.13.1 -> a4396bd6-631c-428e-822a-f2759a50a6df

Received component: 2bda3139-647f-47ff-9c35-ffc16adf3076
Re-keyed component: a4396bd6-631c-428e-822a-f2759a50a6df -> pkg:maven/com.fasterxml.jackson.core/jackson-databind@2.13.1
Joined: pkg:maven/com.fasterxml.jackson.core/jackson-databind@2.13.1 -> VulnerabilityResultAggregate(component=pkg:maven/com.fasterxml.jackson.core/jackson-databind@2.13.1, vulnerabilityResults=[org.acme.model.VulnerablityResult@32678adb, org.acme.model.VulnerablityResult@3d7ef798, org.acme.model.VulnerablityResult@6c994225])
Cache hit: pkg:maven/com.fasterxml.jackson.core/jackson-databind@2.13.1
```

**Comment by syalioune** [comment]
> @syalioune Please don't sweat it, it's still very rough on the edges and has lots of duplicated and unused code. 😅

Duely noted ! patiently waiting to test it 😉

**Review by japurva1502 — APPROVED** [review]
Looks good
Great work Niklas and Alioune !!

**Pull request merged**
